services:
  db:
    image: mysql:8.0
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-bank}
      MYSQL_USER: ${DB_USERNAME:-developer}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_CHARSET: ${DB_CHARSET:-utf8mb4}
    ports:
      - "${DB_PORT:-3306}:3306"
    volumes:
      - data:/var/lib/mysql
    networks:
      - net
    command: >
      --character-set-server=${DB_CHARSET:-utf8mb4}
      --default-authentication-plugin=mysql_native_password
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p$${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  net:
    driver: bridge

volumes:
  data:
    driver: local
